# Default database configurations
schemaName: MONDIAL
rdbmsName:
  - postgresql
defaultKeyName: uid
defaultKeyDomainName: uid_domain
defaultKeyType: int
defaultAttributeName: value
defaultAttributeDomaineName: value_domain
defaultAttributeType: text
useIriAsTableId: true
normalizeDatatype: false
generateOpTable: true
removeThingTable: false
languages:
  - en
