// Settings
:idprefix:
:idseparator: -
:page-component-title: Application for generating a relational database using an ontology
:page-component-name: Ontorela
= {page-component-name}

Historique de l'évolution.

== Version 2.1.0
* Mise à jour de compliance v4.
* Factorisation des services.
* Déplacer les algorithmes de réduction de redondance des axiomes d'association de classe dans monto-library.
* Mise à jour de configuration.
* Mise à jour à monto-library 1.4.0:
  * Ajout des algorithmes de réduction de redondance des axiomes d'association de classe.
  * Ajout de configuration pour la réduction de redondance: reduceRedundancyAxiom.

== Version 2.0.1
* Désactiver les classes de temporalités.

== Version 2.0.0
* Mise à jour des interfaces CLI, ajout de nouvelles fonctions :
    * Générer Ontorel, graphes et rapports: Conserve l'ancien comportement de l'application.
    * Générer Ontorel: Génère l'ontologie normalisée ainsi que les scripts SQL associés à Ontorel.
    * Générer les graphes: Construit un graphe d'ontologie, un graphe de base de données et/ou un graphe ontologique-relationnel d'Ontorel.
    * Générer les rapports et les anomalies: Produit un rapport des anomalies pour l'ontologie et/ou la base de données.

== Version 1.3.1
* Mise à jour des appels de fonctions pour la génération du script OntoRelCat.
* Ajout de l'attribut removeThingTable dans la table Ontorel_db_config, en lien avec la release 1.3.0.

== Version 1.3.0

* Utilisation des IRI pour les identifiants des tables (avec le paramètre useIRIasTableId).
* Retrait de la table et des associations à Thing (avec le paramètre removeThingTable).
* Diverse correction dans OntoRelCat.
* Mise à jour à MOnto 1.3.0 :
    * Génération des identifiants des classes générées par une fonction hash sur l'expression de
      l'axiome complexe correspond.
    * Ajout du chargement d'une ontologie à partir d'un URL.
    * Correction de la normalisation des axiomes complexes à plus qu'un niveau d'imbrication.
    * Élimination des doublons des classes générées par des expressions similaires lors de la
      normalisation des axiomes complexes
* Mise à jour des librairies tierces.

== Version 1.2.2

* Création d'un schéma relationnel pour OntoRelCat
* Génération des tuples l'OntoRelCat pour un OntoRel.

== Version 1.2.1

Mise à jour de MOnto.

== Version 1.1.1

Mise à jour de Gradle et de toutes libraries dépendances.

== Version 1.1.0

* Retrait du numéro artificiel des tables Txxx des vues IRI
* Renommage OntoRelDic pour OntoRelCat.
* Ajout paramètre de configuration pour activer/désactiver la réduction de redondance des axiomes (
  normalizeAxiom).
* Mise à jour MOnto (voir modifications MOnto).

== Version 1.0.0

Version initiale.
