owlFilePath: demo/PHYSIO/HumanBodyWeightAppli-inferred.owl
#loadEquivalentClass: true

annotations:
  labels:
    - "http://www.w3.org/2000/01/rdf-schema#label"
    - "http://purl.obolibrary.org/obo/BFO_0000179"
  definitions:
    - "http://purl.org/dc/elements/1.1/description"
    - "http://purl.obolibrary.org/obo/BFO_0000180"
    - "http://purl.obolibrary.org/obo/IAO_0000115"

classes:
  ## ====================================== PHYSIO ====================================== ##
  # Racines
  - "http://purl.obolibrary.org/obo/PHYSIO_0000083" # Physiological evaluation report
  # Les processus
  - "http://purl.obolibrary.org/obo/humanbodyweight-appli-inf.owl/PHYSIO_0000085" # Physiological evaluation
  #- "http://purl.obolibrary.org/obo/humanbodyweight-appli-inf.owl/PHYSIO_0000091" # Physiological evaluation of patient
  # The measurements
  - "http://purl.obolibrary.org/obo/humanbodyweight-appli-inf.owl/PHYSIO_0000093" # Physiological data item
  - "http://purl.obolibrary.org/obo/PHYSIO_0000008" # Body weight measurement process
  - "http://purl.obolibrary.org/obo/PHYSIO_0000065" # Human body mass measurement datum'
  # Path to all measurements
  - "http://purl.obolibrary.org/obo/IAO_0000027" # data item
  - "http://purl.obolibrary.org/obo/IAO_0000109" # Measurement datum
  - "http://purl.obolibrary.org/obo/IAO_0000032" # Scalar measurement datum
  - "http://purl.obolibrary.org/obo/OBI_0001931" #- Scalar value specification
  - "http://purl.obolibrary.org/obo/IAO_0000003" #- Measurement unit label
  - "http://purl.obolibrary.org/obo/UO_0000002"  ## Mass unit
  ## ====================================== HADO ====================================== ##
  - "http://purl.obolibrary.org/obo/HADO_0000008" # Patient
  - "http://purl.obolibrary.org/obo/IAO_0000577"  # Centrally registered identifier symbol
  - "http://purl.obolibrary.org/obo/HADO_0000006" # Medical record identifier
  # Path to patient
  - "http://purl.obolibrary.org/obo/OBI_0100026" # Organism
  - "http://purl.obolibrary.org/obo/NCBITaxon_9606" # Homo sapiens
  #- "http://purl.obolibrary.org/obo/OBI_0000093" # Patient role

objectProperties:
  - "http://purl.obolibrary.org/obo/BFO_0000051"  # has part
  - "http://purl.obolibrary.org/obo/BFO_0000050"  # part of
  - "http://purl.obolibrary.org/obo/BFO_0000066"  # occurs in
  - "http://purl.obolibrary.org/obo/RO_0000052"   # inheres in
  - "http://purl.obolibrary.org/obo/RO_0000057"   # has participant
  - "http://purl.obolibrary.org/obo/IAO_0000039"  # has measurement unit label
  - "http://purl.obolibrary.org/obo/IAO_0000136"  # is about
  - "http://purl.obolibrary.org/obo/IAO_0000219"  # denotes
  - "http://purl.obolibrary.org/obo/OBI_0001938"  # has value specification
  - "http://purl.obolibrary.org/obo/OBI_0000299"  # has_specified_output
  - "http://purl.obolibrary.org/obo/OBI_0000312"  # is_specified_output_of
  - "http://purl.obolibrary.org/obo/PDRO-P3_1000001"  # has sublevel part
  - "http://purl.obolibrary.org/obo/humanbodyweight-appli-inf.owl/PHYSIO_0000089"  # has evaluant