owlFilePath: demo/PDRO/PDRO.owl

annotations:
  labels:
    - "http://www.w3.org/2000/01/rdf-schema#label"
    - "http://purl.obolibrary.org/obo/BFO_0000179"
  definitions:
    - "http://purl.org/dc/elements/1.1/description"
    - "http://purl.obolibrary.org/obo/BFO_0000180"
    - "http://purl.obolibrary.org/obo/IAO_0000115"

classes:
  - "http://purl.obolibrary.org/obo/PDRO_0000001" # Health care prescription
  - "http://purl.obolibrary.org/obo/PDRO_0000024" # Drug prescription
  - "http://purl.obolibrary.org/obo/PDRO_0000003" # Patient identification
  - "http://purl.obolibrary.org/obo/PDRO_0000005" # Document creation time identification
  # Drug administration specification
  - "http://purl.obolibrary.org/obo/PDRO_0010022"
  # Drug product specification
  - "http://purl.obolibrary.org/obo/PDRO_0000060"
  - "http://purl.obolibrary.org/obo/PDRO_0000097" # Drug identification number
  - "http://purl.obolibrary.org/obo/PDRO_0000044" # Drug product name
  - "http://purl.obolibrary.org/obo/PDRO_0040002" # Active ingredient name
  # Prescribed dosing specification
  - "http://purl.obolibrary.org/obo/PDRO_0000103"
  # Dose administration specification
  - "http://purl.obolibrary.org/obo/PDRO_0000190"
  - "http://purl.obolibrary.org/obo/PDRO_0000190" # Dose quantification specification
  # Condition
  - "http://purl.obolibrary.org/obo/PDRO_0000129"
  - "http://purl.obolibrary.org/obo/PDRO_0000127" # Continuing drug admistration condition
  - "http://purl.obolibrary.org/obo/PDRO_0000128" # Starting drug administration condition
  # TEST - "http://purl.obolibrary.org/obo/DRON_00000005" # drug product

objectProperties:
  - "http://purl.obolibrary.org/obo/BFO_0000051"   # has part
  - "http://purl.obolibrary.org/obo/OBI_0001938"   # has value specification
  - "http://purl.obolibrary.org/obo/IAO_0000142"   # mentions
  - "http://purl.obolibrary.org/obo/IAO_0000039"   # has measurement unit label
  - "http://purl.obolibrary.org/obo/RO_0000057"    # has participant
  # TEST - "http://purl.obolibrary.org/obo/IAO_0000136"   # is about
