# Default database configurations
schemaName: PDRO
rdbmsName:
  - postgresql
defaultKeyName: uid
defaultKeyDomainName: uid_domain
defaultKeyType: UUID
defaultAttributeName : value
defaultAttributeDomaineName: value_domain
defaultAttributeType: TEXT
maxIdentifierLength: 60
normalizeDatatype: false
generateOpTable: true
removeThingTable: false
useIriAsTableId: true
languages:
  - en
  - fr

