owlFilePath: demo/ENVO/envo_merged.owl

annotations:
  labels:
    - "http://www.w3.org/2000/01/rdf-schema#label"
  definitions:
    - "http://purl.org/dc/elements/1.1/description"

classes:
  - "http://purl.obolibrary.org/obo/ENVO_01000306" #[freshwater environment]
  - "http://purl.obolibrary.org/obo/ENVO_01000307" #[saline water environment]
  - "http://purl.obolibrary.org/obo/ENVO_01001043" #[hypersaline water environment]
  - "http://purl.obolibrary.org/obo/ENVO_01000999" #[rhizosphere environment]
  - "http://purl.obolibrary.org/obo/ENVO_01001000" #[environmental system determined by an organism]
  - "http://purl.obolibrary.org/obo/ENVO_01001001" #[plant-associated environment]
  - "http://purl.obolibrary.org/obo/ENVO_01001041" #[fungi-associated environment]
  - "http://purl.obolibrary.org/obo/ENVO_01001002" #[animal-associated environment]
  - "http://purl.obolibrary.org/obo/ENVO_01001001" #[plant-associated environment]
  - "http://purl.obolibrary.org/obo/ENVO_01001002" #[animal-associated environment]
  - "http://purl.obolibrary.org/obo/ENVO_01001028" #[sediment permeated by freshwater]
  - "http://purl.obolibrary.org/obo/ENVO_01001029" #[fecal environment]
  - "http://purl.obolibrary.org/obo/ENVO_01001030" #[environment determined by a metazoan secretion]
  - "http://purl.obolibrary.org/obo/ENVO_01001031" #[environment determined by a plant substance]
  - "http://purl.obolibrary.org/obo/ENVO_01001032" #[environment determined by a biofilm on a plant surface]
  - "http://purl.obolibrary.org/obo/ENVO_01001033" #[digestive tract environment]
  - "http://purl.obolibrary.org/obo/ENVO_01001034" #[environment determined by a biofilm on an animal surface]
  - "http://purl.obolibrary.org/obo/ENVO_01001035" #[environment determined by a biofilm on a fungal surface]
  - "http://purl.obolibrary.org/obo/ENVO_01001036" #[sediment permeated by saline water]
  - "http://purl.obolibrary.org/obo/ENVO_01001041" #[fungi-associated environment]
  - "http://purl.obolibrary.org/obo/ENVO_01001042" #[sterile water environment]
  - "http://purl.obolibrary.org/obo/ENVO_01001043" #[hypersaline water environment]
  - "http://purl.obolibrary.org/obo/ENVO_01001044" #[soil environment]
  - "http://purl.obolibrary.org/obo/ENVO_01001046" #[planetary subsurface environment]
  - "http://purl.obolibrary.org/obo/ENVO_01001047" #[non-saline planetary subsurface environment]
  - "http://purl.obolibrary.org/obo/ENVO_01001047" #[non-saline planetary subsurface environment]
  - "http://purl.obolibrary.org/obo/ENVO_01001048" #[sediment environment]
  - "http://purl.obolibrary.org/obo/ENVO_01001050" #[saline sediment environment]
  - "http://purl.obolibrary.org/obo/ENVO_01001049" #[non-saline sediment environment]
  - "http://purl.obolibrary.org/obo/ENVO_01001049" #[non-saline sediment environment]
  - "http://purl.obolibrary.org/obo/ENVO_01001050" #[saline sediment environment]
  - "http://purl.obolibrary.org/obo/ENVO_01001051" #[environment determined by a biofilm on a non-saline surface]
  - "http://purl.obolibrary.org/obo/ENVO_01001052" #[aerosol environment]
  - "http://purl.obolibrary.org/obo/ENVO_01001054" #[non-saline aerosol environment]
  - "http://purl.obolibrary.org/obo/ENVO_01001053" #[saline aerosol environment]
  - "http://purl.obolibrary.org/obo/ENVO_01001053" #[saline aerosol environment]
  - "http://purl.obolibrary.org/obo/ENVO_01001054" #[non-saline aerosol environment]
  - "http://purl.obolibrary.org/obo/ENVO_01001055" #[environment associated with an animal part or small animal]
  - "http://purl.obolibrary.org/obo/ENVO_01001056" #[environment determined by a biofilm on a saline surface]
  - "http://purl.obolibrary.org/obo/ENVO_01001057" #[environment associated with a plant part or small plant]
  - "http://purl.obolibrary.org/obo/ENVO_01001031" #[environment determined by a plant substance]
  - "http://purl.obolibrary.org/obo/ENVO_01001058" #[environment associated with a fungal tissue]
  - "http://purl.obolibrary.org/obo/ENVO_01001041" #[fungi-associated environment]
  - "http://purl.obolibrary.org/obo/ENVO_01001059" #[mock community]
  - "http://purl.obolibrary.org/obo/ENVO_01001060" #[single strain cell culture]
