owlFilePath: https://raw.githubusercontent.com/OpenLHS/HDRN/main/HDRN-full.owl
loadEquivalentClass: false
annotations:
  labels:
    - "http://www.w3.org/2000/01/rdf-schema#label"
  definitions:
    - "http://purl.obolibrary.org/obo/IAO_0000115"
    - "http://purl.obolibrary.org/obo/IAO_0000600"