# Database configurations
schemaName: HDRN
rdbmsName:
  - postgresql
defaultKeyName: uid
defaultKeyDomainName: uid_domain
defaultKeyType: UUID
defaultAttributeName: value
defaultAttributeDomaineName: value_domain
defaultAttributeType: TEXT
maxIdentifierLength: 60
useIRIasTableId: true
normalizeDatatype: false
normalizeAxiom: false
generateOpTable: false
languages:
  - en
  - fr