owlFilePath: /Depots/Kagou/Logitheques/OntoRelA/jeux/demo/UNIVBENCH/univ-bench.owl

annotations:
  labels:
    - "http://www.w3.org/2000/01/rdf-schema#label"
  definitions:
    - "http://purl.org/dc/elements/1.1/description"
