# Default database configurations
schemaName: PDRO
rdbmsName:
  - postgresql
defaultKeyName: uid
defaultKeyDomainName: uid_domain
defaultKeyType: UUID
defaultAttributeName : value
defaultAttributeDomaineName: value_domain
defaultAttributeType: TEXT
normalizeDatatype: false
removeThingTable: false
useIRIasTableId: true
generateOpTable: true
languages:
  - en
  - fr
