owlFilePath: /Depots/Kagou/Logitheques/OntoRelA/jeux/demo/PDRO/PDRO.owl

annotations:
  labels:
    - "http://www.w3.org/2000/01/rdf-schema#label"
    - "http://purl.obolibrary.org/obo/BFO_0000179"
  definitions:
    - "http://purl.org/dc/elements/1.1/description"
    - "http://purl.obolibrary.org/obo/BFO_0000180"
    - "http://purl.obolibrary.org/obo/IAO_0000115"

classes:
  - "http://purl.obolibrary.org/obo/PDRO_0000001" # Health care prescription
  - "http://purl.obolibrary.org/obo/PDRO_0000024" # Drug prescription
  - "http://purl.obolibrary.org/obo/IAO_0000302"  # Author identification
  - "http://purl.obolibrary.org/obo/PDRO_0000003" # Patient identification
  - "http://purl.obolibrary.org/obo/PDRO_0000005" # Document creation time identification
  - "http://purl.obolibrary.org/obo/PDRO_0000007" # Drug administration and dispensing specification
  # Drug administration specification
  - "http://purl.obolibrary.org/obo/PDRO_0010022"
  # Drug product specification
  - "http://purl.obolibrary.org/obo/PDRO_0000060"
  - "http://purl.obolibrary.org/obo/PDRO_0000044" # Drug product name
  - "http://purl.obolibrary.org/obo/PDRO_0000051" # Drug dose form specification
  - "http://purl.obolibrary.org/obo/PDRO_0000097" # Drug identification number
  - "http://purl.obolibrary.org/obo/PDRO_0000053" # Drug active indredient specification
  - "http://purl.obolibrary.org/obo/PDRO_0040002" # Active ingredient name
  # Drug strengh specification
  - "http://purl.obolibrary.org/obo/PDRO_0000022"
  # Prescribed dosing specification
  - "http://purl.obolibrary.org/obo/PDRO_0000103"
  # Dose administration specification
  - "http://purl.obolibrary.org/obo/PDRO_0000190"
  - "http://purl.obolibrary.org/obo/PDRO_0000030" # Duration of administration specification
  - "http://purl.obolibrary.org/obo/PDRO_0000020" # Route of administration specification
  - "http://purl.obolibrary.org/obo/PDRO_0010080" # Route of administration category specification
  # Dose quantification specification
  - "http://purl.obolibrary.org/obo/PDRO_0000123"
  - "http://purl.obolibrary.org/obo/PDRO_0000094" # Site of drug administration specification
  - "http://purl.obolibrary.org/obo/PDRO_0000114" # Site of administration category specification
  # Drug dispensing specification
  - "http://purl.obolibrary.org/obo/PDRO_0000096"
  # Les conditions
  - "http://purl.obolibrary.org/obo/PDRO_0000129"
  - "http://purl.obolibrary.org/obo/PDRO_0000127"

objectProperties:
  - "http://purl.obolibrary.org/obo/BFO_0000051"   # has part
  - "http://purl.obolibrary.org/obo/OBI_0001938"   # has value specification
  - "http://purl.obolibrary.org/obo/IAO_0000039"   # has measurement unit label
  - "http://purl.obolibrary.org/obo/RO_0000057"    # has participant
