owlFilePath: demo/MONDIAL/mondial-meta.n3

annotations:
  labels:
    - "http://www.w3.org/2000/01/rdf-schema#label"
  definitions:
    - "http://purl.org/dc/elements/1.1/description"

classes:
  - "f://m#City"
  - "f://m#Country"
  - "f://m#Province"
  - "f://m#Continent"
  - "f://m#Border"
  - "f://m#River"
  - "f://m#Lake"
  - "f://m#Sea"
  - "f://m#Water"
  - "f://m#Mountain"
  - "f://m#PopulationCount"
  - "f://m#Religion"
  - "f://m#BelievedBy"
